// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: graph.sql

package db

import (
	"context"
)

const getGraphEdges = `-- name: GetGraphEdges :many
WITH symbol_freq AS (
    SELECT s.name
    FROM symbols s
    JOIN documents d ON d.id = s.doc_id
    WHERE d.repo_id = ?
    GROUP BY s.name
    HAVING COUNT(DISTINCT s.doc_id) <= 20
)
SELECT
  r.doc_id AS source_id,
  d.path AS source_path,
  s.doc_id AS target_id,
  d2.path AS target_path,
  COUNT(*) AS weight
FROM refs r
JOIN symbols s ON s.name = r.name
JOIN documents d ON d.id = r.doc_id
JOIN documents d2 ON d2.id = s.doc_id
WHERE d.id != d2.id
  AND d.repo_id = ?
  AND d2.repo_id = ?
  AND r.name IN (SELECT name FROM symbol_freq)
  AND s.name IN (SELECT name FROM symbol_freq)
GROUP BY r.doc_id, s.doc_id
ORDER BY weight DESC
LIMIT 1000
`

type GetGraphEdgesParams struct {
	RepoID   int64 `json:"repo_id"`
	RepoID_2 int64 `json:"repo_id_2"`
	RepoID_3 int64 `json:"repo_id_3"`
}

type GetGraphEdgesRow struct {
	SourceID   int64  `json:"source_id"`
	SourcePath string `json:"source_path"`
	TargetID   int64  `json:"target_id"`
	TargetPath string `json:"target_path"`
	Weight     int64  `json:"weight"`
}

func (q *Queries) GetGraphEdges(ctx context.Context, arg GetGraphEdgesParams) ([]GetGraphEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraphEdges, arg.RepoID, arg.RepoID_2, arg.RepoID_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGraphEdgesRow{}
	for rows.Next() {
		var i GetGraphEdgesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourcePath,
			&i.TargetID,
			&i.TargetPath,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGraphEdgesFromTable = `-- name: GetGraphEdgesFromTable :many
SELECT
  ge.source_doc_id AS source_id,
  d.path AS source_path,
  ge.target_doc_id AS target_id,
  d2.path AS target_path,
  ge.weight
FROM graph_edges ge
JOIN documents d ON d.id = ge.source_doc_id
JOIN documents d2 ON d2.id = ge.target_doc_id
WHERE ge.repo_id = ?
  AND ge.kind = 'references'
ORDER BY ge.weight DESC
LIMIT 1000
`

type GetGraphEdgesFromTableRow struct {
	SourceID   int64  `json:"source_id"`
	SourcePath string `json:"source_path"`
	TargetID   int64  `json:"target_id"`
	TargetPath string `json:"target_path"`
	Weight     int64  `json:"weight"`
}

func (q *Queries) GetGraphEdgesFromTable(ctx context.Context, repoID int64) ([]GetGraphEdgesFromTableRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraphEdgesFromTable, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGraphEdgesFromTableRow{}
	for rows.Next() {
		var i GetGraphEdgesFromTableRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourcePath,
			&i.TargetID,
			&i.TargetPath,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGraphNodes = `-- name: GetGraphNodes :many
SELECT id, path, repo_id FROM documents
WHERE repo_id = ?
ORDER BY id
`

type GetGraphNodesRow struct {
	ID     int64  `json:"id"`
	Path   string `json:"path"`
	RepoID int64  `json:"repo_id"`
}

func (q *Queries) GetGraphNodes(ctx context.Context, repoID int64) ([]GetGraphNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraphNodes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGraphNodesRow{}
	for rows.Next() {
		var i GetGraphNodesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.RepoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
