// Code generated by sqlc. DO NOT EDIT.
// source: graph.sql

package db

import (
	"context"
)

const getGraphEdges = `-- name: GetGraphEdges :many
SELECT
  r.doc_id,
  d.path,
  s.doc_id,
  d2.path,
  COUNT(*) AS weight
FROM refs r
JOIN symbols s ON s.name = r.name
JOIN documents d ON d.id = r.doc_id
JOIN documents d2 ON d2.id = s.doc_id
WHERE d.id != d2.id
  AND d.repo_id = ?
  AND d2.repo_id = ?
GROUP BY r.doc_id, s.doc_id
ORDER BY weight DESC
LIMIT 1000
`

func (q *Queries) GetGraphEdges(ctx context.Context, repoID int64) ([]GetGraphEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraphEdges, repoID, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGraphEdgesRow
	for rows.Next() {
		var i GetGraphEdgesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourcePath,
			&i.TargetID,
			&i.TargetPath,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGraphNodes = `-- name: GetGraphNodes :many
SELECT id, path, repo_id FROM documents
WHERE repo_id = ?
ORDER BY id
`

type GetGraphNodesRow struct {
	ID     int64  `json:"id"`
	Path   string `json:"path"`
	RepoID int64  `json:"repo_id"`
}

func (q *Queries) GetGraphNodes(ctx context.Context, repoID int64) ([]GetGraphNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGraphNodes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGraphNodesRow
	for rows.Next() {
		var i GetGraphNodesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.RepoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
