// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbols.sql

package db

import (
	"context"
	"database/sql"
)

const createSymbol = `-- name: CreateSymbol :one
INSERT INTO symbols (doc_id, name, kind, line, col)
VALUES (?, ?, ?, ?, ?)
RETURNING id, doc_id, name, kind, line, col
`

type CreateSymbolParams struct {
	DocID int64  `json:"doc_id"`
	Name  string `json:"name"`
	Kind  string `json:"kind"`
	Line  int64  `json:"line"`
	Col   int64  `json:"col"`
}

func (q *Queries) CreateSymbol(ctx context.Context, arg CreateSymbolParams) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, createSymbol,
		arg.DocID,
		arg.Name,
		arg.Kind,
		arg.Line,
		arg.Col,
	)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.Name,
		&i.Kind,
		&i.Line,
		&i.Col,
	)
	return i, err
}

const deleteSymbolsByDoc = `-- name: DeleteSymbolsByDoc :exec
DELETE FROM symbols
WHERE doc_id = ?
`

func (q *Queries) DeleteSymbolsByDoc(ctx context.Context, docID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSymbolsByDoc, docID)
	return err
}

const findSymbolsByName = `-- name: FindSymbolsByName :many
SELECT s.id, s.doc_id, s.name, s.kind, s.line, s.col, d.path, d.repo_id, r.name AS repo_name
FROM symbols s
JOIN documents d ON d.id = s.doc_id
JOIN repositories r ON r.id = d.repo_id
WHERE s.name LIKE ? || '%'
ORDER BY s.name, d.path
`

type FindSymbolsByNameRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindSymbolsByName(ctx context.Context, dollar_1 sql.NullString) ([]FindSymbolsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, findSymbolsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSymbolsByNameRow{}
	for rows.Next() {
		var i FindSymbolsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Kind,
			&i.Line,
			&i.Col,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSymbolsByNameAndKind = `-- name: FindSymbolsByNameAndKind :many
SELECT s.id, s.doc_id, s.name, s.kind, s.line, s.col, d.path, d.repo_id, r.name AS repo_name
FROM symbols s
JOIN documents d ON d.id = s.doc_id
JOIN repositories r ON r.id = d.repo_id
WHERE s.name LIKE ? || '%' AND s.kind = ?
ORDER BY s.name, d.path
`

type FindSymbolsByNameAndKindParams struct {
	Column1 sql.NullString `json:"column_1"`
	Kind    string         `json:"kind"`
}

type FindSymbolsByNameAndKindRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindSymbolsByNameAndKind(ctx context.Context, arg FindSymbolsByNameAndKindParams) ([]FindSymbolsByNameAndKindRow, error) {
	rows, err := q.db.QueryContext(ctx, findSymbolsByNameAndKind, arg.Column1, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSymbolsByNameAndKindRow{}
	for rows.Next() {
		var i FindSymbolsByNameAndKindRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Kind,
			&i.Line,
			&i.Col,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSymbolsByRepo = `-- name: FindSymbolsByRepo :many
SELECT s.id, s.doc_id, s.name, s.kind, s.line, s.col, d.path, d.repo_id, r.name AS repo_name
FROM symbols s
JOIN documents d ON d.id = s.doc_id
JOIN repositories r ON r.id = d.repo_id
WHERE r.name = ? AND s.name LIKE ? || '%'
ORDER BY s.name, d.path
`

type FindSymbolsByRepoParams struct {
	Name    string         `json:"name"`
	Column2 sql.NullString `json:"column_2"`
}

type FindSymbolsByRepoRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindSymbolsByRepo(ctx context.Context, arg FindSymbolsByRepoParams) ([]FindSymbolsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, findSymbolsByRepo, arg.Name, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSymbolsByRepoRow{}
	for rows.Next() {
		var i FindSymbolsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Kind,
			&i.Line,
			&i.Col,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSymbolsByRepoAndKind = `-- name: FindSymbolsByRepoAndKind :many
SELECT s.id, s.doc_id, s.name, s.kind, s.line, s.col, d.path, d.repo_id, r.name AS repo_name
FROM symbols s
JOIN documents d ON d.id = s.doc_id
JOIN repositories r ON r.id = d.repo_id
WHERE r.name = ? AND s.name LIKE ? || '%' AND s.kind = ?
ORDER BY s.name, d.path
`

type FindSymbolsByRepoAndKindParams struct {
	Name    string         `json:"name"`
	Column2 sql.NullString `json:"column_2"`
	Kind    string         `json:"kind"`
}

type FindSymbolsByRepoAndKindRow struct {
	ID       int64  `json:"id"`
	DocID    int64  `json:"doc_id"`
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	Line     int64  `json:"line"`
	Col      int64  `json:"col"`
	Path     string `json:"path"`
	RepoID   int64  `json:"repo_id"`
	RepoName string `json:"repo_name"`
}

func (q *Queries) FindSymbolsByRepoAndKind(ctx context.Context, arg FindSymbolsByRepoAndKindParams) ([]FindSymbolsByRepoAndKindRow, error) {
	rows, err := q.db.QueryContext(ctx, findSymbolsByRepoAndKind, arg.Name, arg.Column2, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSymbolsByRepoAndKindRow{}
	for rows.Next() {
		var i FindSymbolsByRepoAndKindRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Name,
			&i.Kind,
			&i.Line,
			&i.Col,
			&i.Path,
			&i.RepoID,
			&i.RepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
